[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/demo"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
